import { Acme, Poppins,Nunito } from "next/font/google";
import "./globals.css";
import Header from "../components/common/Header";
import Footer from "@/components/common/Footer";
import { CartProvider } from "@/context/CartContext";
import CartDrawer from "@/components/common/CartDrawer";
import WhatsApp from "@/components/common/WhatsApp";


const acme = Acme({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-acme",
});


const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700",'900'],
  variable: "--font-poppins",
});

const nunito = Nunito({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700', '900'],
  variable: '--font-nunito',
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${poppins.variable} ${acme.variable} ${nunito.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <CartProvider>
          <Header/>
          <CartDrawer/>
          {children}
          <WhatsApp/>
          <Footer/>
        </CartProvider>
      </body>
    </html>
  );
}
